apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mk-eks-cluster
  region: ap-south-1

nodeGroups:
   - name: mk1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: keycloudclass
  
   - name: ng-mixed
     minSize: 1
     maxSize: 3
     instancesDistribution:
       maxPrice: 0.010
       instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: keycloudclass
